=== 4DvAnCeBoY/isis/documentation-old/notes/document.dtd
<!-- existing entities - ->
<!ENTITY lt "">
<!ENTITY gt "">
<!ENTITY amp "">
-->


<!-- entities -->
<!ENTITY % text "#PCDATA|em|ital|rephrase">

<!ENTITY % code "class|variable|method|code">

<!ENTITY % ui "object|field|menu">

<!ENTITY % para-elements "%text;|%code;|%ui;|path|property|
   note|comment|weblink|email|ref|see">

<!ENTITY  % section-elements "subheading|para|list|program-listing|
   command-listing|property-listing|inline-graphic|figure|panel|
   comment|anchor|index|anchor|biblio|table">

<!ELEMENT webpage (comment?, cross-ref?, (section|block|%section-elements;)*)>
<!ATTLIST webpage
        title CDATA #IMPLIED
        date CDATA #IMPLIED
        label CDATA #IMPLIED>

<!ELEMENT cross-ref (see)*>

<!ELEMENT table (row*)>
<!ELEMENT row (empty-cell|cell)*>
<!ELEMENT empty-cell EMPTY>
<!ELEMENT cell (%para-elements;)*>

<!-- sections - each document is split into sections, each section can
contain other sections -->
<!ELEMENT section (comment?,index*,(intro|para),(section|(%section-elements;))*)>
<!ATTLIST section
        title CDATA #REQUIRED
        label CDATA #IMPLIED
        numbered (on|off) "on">

<!ELEMENT block ((section|(%section-elements;))*)>


<!-- main textual elements
   intro - introductory text
   subheading - 
   para - standard paragraph -->

<!ELEMENT intro (para|index|comment)*>

<!ELEMENT subheading (%text;)*>
<!ATTLIST subheading
        label CDATA #IMPLIED>

<!ELEMENT para (%para-elements;)*>

<!ELEMENT list (para|item|comment|index)*>
<!ELEMENT item (para|index|program-listing|command-listing|screenshot|note)*>

<!ELEMENT comment ANY> <!-- authors notes -->

<!ELEMENT note (%para-elements;)*> <!-- footnotes -->

<!ELEMENT program-listing (%text;|listing-note)*>

<!ELEMENT listing-note (%para-elements;)*> 

<!ELEMENT command-listing (%text;)*>

<!ELEMENT property-listing (%text;)*>

<!ELEMENT biblio (%para-elements;)*> <!-- bibliographic reference -->
<!ATTLIST biblio
   name CDATA #REQUIRED
   year CDATA #REQUIRED
   url CDATA #IMPLIED>



<!-- graphics/images 
   - a figure is a standalone labelled images
   - an inline graphic should be placed in-situ (without any label) -->
<!ELEMENT figure (description?,(caption|%section-elements;)*)>
<!ATTLIST figure
	width CDATA  "100"
   	wrap (yes|no) "no"
	side (left|centre|right|inside|outside) "right"	
        fileref CDATA #REQUIRED
        label CDATA #IMPLIED>

<!ELEMENT description (%text;)*>

<!ELEMENT inline-graphic (description?,(annotation)*)>
<!ATTLIST inline-graphic
   width CDATA  "80"
   	wrap (yes|no) "no"
   	side (left|centre|right|inside|outside) "centre"
      fileref CDATA #REQUIRED>
	
<!ELEMENT annotation (para)*>
<!ATTLIST annotation
	x CDATA #REQUIRED
	y CDATA #REQUIRED>
	

<!-- panel
   - a standalone labelled section of text and image -->
<!ELEMENT panel (caption,(subheading|para|list|program-listing|
        command-listing|property-listing|inline-graphic|comment|index)*)>
<!ATTLIST panel
        label CDATA #IMPLIED>

<!ELEMENT caption (%para-elements;)*>




<!-- subelements - these are all found within paras, listings etc. -->
<!ELEMENT em (#PCDATA)>  <!-- emphasis -->
<!ELEMENT ital (#PCDATA)>  <!-- italics -->

<!-- class definitions -->
<!ELEMENT code (#PCDATA)>  <!-- Java code -->

<!ELEMENT class (%text;)*>

<!ELEMENT method (%text;)*>

<!ELEMENT variable (%text;)*>

<!-- visible aspects -->
<!ELEMENT object (#PCDATA)>

<!ELEMENT menu (#PCDATA)>

<!ELEMENT field (#PCDATA)>

<!-- other programming elements - filepaths and property entries -->
<!ELEMENT path (%text;)*>

<!ELEMENT property (%text;)*>


<!-- links -->
<!-- internal - to other parts of the document -->
<!ELEMENT see (%para-elements;)*>
<!ATTLIST see
   file CDATA #IMPLIED
   label CDATA #REQUIRED
   comment CDATA #IMPLIED>

<!ELEMENT anchor EMPTY>
<!ATTLIST anchor
        label CDATA #REQUIRED>

<!-- external - to web sites -->
<!ELEMENT weblink (#PCDATA)>
<!ATTLIST weblink
        address CDATA #REQUIRED>

<!-- bibliographic reference -->
<!ELEMENT ref EMPTY>
<!ATTLIST ref
        name CDATA #REQUIRED
        year CDATA #REQUIRED>

<!-- index references -->
<!ELEMENT index (term, usage?)>

<!ELEMENT term (%para-elements;)*>

<!ELEMENT usage (%para-elements;)*>

<!-- email -->
<!ELEMENT email (#PCDATA)>
<!ATTLIST email
        address CDATA #REQUIRED
        subject CDATA #IMPLIED
        body CDATA #IMPLIED>

=== 4DvAnCeBoY/isis/documentation-old/notes/security.xml
<?xml version='1.0'?>
<!DOCTYPE webpage SYSTEM "./document.dtd">

<webpage title="Security" label="themes" date="10-Mar-04">
	
<subheading>Users and Roles</subheading>

	<para>The org.nakedobjects.security package provides a number of new classes
		concerned with security.  The most significant of these are User and Role.
		A User represents a specific individual, and will define their user name
		and password.  Each User object can have a number of Role objects 
		associated with it. </para>
		
<subheading>Log-in</subheading>
	
	<para>When a deployed Naked Object system (i.e. a Standalone or ???) is run, the user will be required
		to log-in with a username and password.  (No log-in is required for
		an Exploration, in order to keep the exploration cycle as simple as possible).
	</para>
	
	<para>TBD  -  changing your password</para>
	
<subheading>Default roles:  sysadmin and guest</subheading>

	<para>All deployed systems are provided, by default with two roles:  sysadmin
		and guest, and with two Users of the same name.  [?? How are the passwords
		for sysadmin and guest specified??].  Only the systems administrator
		(sysadmin) can create new Users, new Roles, or assign new Roles to an
		existing User.  The systems administrators may also be given additional
		specific rights or responsibilities by the application.</para>
		
	<para>Guest is a kind of default user role:  all Users automatically have
		the role of 'guest'.  Any anyone can log in as the user 'guest' provided
		they know the password (which is usually quite widely disseminated). Guest
		should therefore be considered as a zero-security role.  Given the 
			<see label="subtractive-control">subractive
		style of control</see> adopted by Naked Objects, any field or action that
		has no form of control specified will be accessible to the guest role. </para>

	<para>Note to Rob:  there should therefore be a way of disabling the
		guest log-in for some systems.</para>

<subheading>Creating new Roles</subheading>

<para>Although new instances of Role are created by 
	</para>
	
	
	
	<para>Accessing users and roles from within an application</para>
	
	<para>Defining the 'root object' for a user</para>

</webpage>

=== 4DvAnCeBoY/isis/documentation-old/notes/context.xml
<?xml version='1.0'?>
<!DOCTYPE webpage SYSTEM "./document.dtd">

<webpage title="Contexts" label="contexts" date="10-Mar-04">
	
<para>In Naked Objects (1.3+), a Context is a convenient way to hold a collection of
	Naked Object classes and instances. If an organistion makes substantial use
	of the Naked Objects approach, it is likely that each user will end up having
	multiple contexts, such as an Email context, an Expenses Processing context, a Customer Service
	context and so forth.</para>
	
<subheading>Contexts vs. applications</subheading>
	
<para>It might be convenient to think of Contexts as applications:  there
	are certainly some similarities.  However, we have chosen to call them
	Contexts because there are also some differences from the conventional
	notion of applications:</para>
	
<list>
	<para>Like applications, a user can have multiple contexts open at the
		same time.  A Context may fill the screen, or the user may have multiple
		contexts open in separate windows.</para>
		
	<para>Contexts are not mutually exclusive.  The same classes and/or instances may appear
		in multiple cotexts (e.g. the CostCentre class may be used in the Expenses
		Processing, Time Recording and Project Management Contexts).  It is possible
		to move or copy objects, or specific Views of objects, between Contexts.</para>
	
	<para>Contexts can be recursive.  Since a Context is just another Naked Object
		it is possible for any Context to hold a reference to any other Context.</para>
	
	<para>Contexts can be user defined.  Although users may be issued with some
		standard Contexts by the systems administrator, they may also define their
		own Contexts:  which may cover just a sub-set of the standard contxt functionality,
		may be a super-set of standard contexts, or just an arbitrary collection of classes
		and objects for that user.  (In the last sense, Contexts can also be
		thought of as similar to folders in a conventional desktop metaphor). </para>
	
	<para>Contexts can be visually represented in several forms. Like any other
		Naked Object, it is possible to view a Context through more than one
		Viewer.  The default viewer for a Context is based on the popular desktop metaphor:  
		allowing the user to position the various contained objects in two
		dimensions.  Alternatives include th Form view and the Tree Browswer view.</para>
	
</list>
	
<subheading>Starting Context</subheading>

<para>In a deployed application, when a user logs on, they will be taken into
	their starting context.  This is specified in the 'root object' field in
	 the User object, and can only be changed by the 
	 	<see label="sysadmin">systems administrator</see>.
	 Strictly speaking, the root object does not have to be a Context at all:  it could
	 be any Naked Object, such as a particular Employee or Customer instance. 
	 However, since the root object must provide the means of navigating to
	 any other object or class that the user needs to access, it is usual to
	 make the root object a Context. Where there are multiple Contexts it can be
	 helpful to think of the one defined as the user's root object as being like a 'portal'.
	 Note, however, that because Contexts can be recursive, there is no structural difference
	 between a portal context and any other context. </para>
	 
	 <para>It is always possible to get back to the starting context by
	 	[doing what?] </para>
	
<subheading>Creating a Context</subheading>

<para>A Context can be created manually or programmatically.  Manually, the systems administrator
	(who's starting context is created and populated automatically by the framework)
	can create a new instance of the class DefaultContext  [??Rename this to GenericContext ??].  
	Into this new Context the SystemsAdministrator can drag instances of NakedClass 
	(i.e. representing the business classes that the user needs access to in that Context) as well as
	any other NakedObject instances for convenience.  The systems administrator can then define this
	newly created Context as the root object for a particular user, or if one already exists can drag
	the next context into the existing one.</para>
	
<para>An instance of Context can only be associated with one user  -  because it can potentially hold
	objects specific to that user.  However, the clone method can be used to create a similar Context
	for another user.</para>
	
<para>Creating contexts programmatically . . . </para>

<subheading>Specialised Contexts</subheading>

<para>Instead of using GenericContext, the programmer may create a specialised Context, by extending
	the AbstractContext class.  In addition to holding the generic list of classes and list of object references, a specialised
	context may have dedicate value, object reference, or collection fields.  In our Expenses example
	application, ExpensesContext has fields for:  My Claims, Claims To Approve, My Cost Centres
	and so forth.  These are not just for the convenience of the user:  those fields are accessed directly
	by other objects in the application.  For example, when a Claim is submitted for approval, the method
	adds the claim to the 'Claims To Approve' field of the claimant's manager.  Thus, a specialised
	Context is key to implementing workflows.</para>

</webpage>
