=== 4DvAnCeBoY/isis/documentation/src/documentation.dtd
<!-- existing entities -->
<!ENTITY lt "">
<!ENTITY gt "">
<!ENTITY amp "">


<!-- entities -->
<!ENTITY % text "#PCDATA|em|ital|rephrase">

<!ENTITY % code "class|variable|method|code">

<!ENTITY % ui "object|field|menu">

<!ENTITY % para-elements "%text;|%code;|%ui;|path|property|
   note|anchor|comment|weblink|ref|see">

<!ENTITY  % section-elements "subheading|para|list|program-listing|
   command-listing|property-listing|inline-graphic|figure|panel|
   comment|index|anchor|biblio">


<!-- sections - each document is split into sections, each section can
contain other sections -->
<!ELEMENT section (title, comment?,index*,(intro|para),(section|(%section-elements;))*)>
<!ATTLIST section
        label CDATA #IMPLIED
        numbered (on|off) "on">

<!ELEMENT title (%text;)*>


<!-- main textual elements
   intro - introductory text
   subheading - 
   para - standard paragraph -->

<!ELEMENT intro (para|index|comment)*>

<!ELEMENT subheading (%text;)*>

<!ELEMENT para (%para-elements;)*>

<!ELEMENT list (para|item|comment|index|el)*>
<!ELEMENT el (#PCDATA)*>
<!ELEMENT item (para|index|program-listing|command-listing|screenshot|note)*>

<!ELEMENT comment ANY> <!-- authors notes -->

<!ELEMENT note (%para-elements;)*> <!-- footnotes -->

<!ELEMENT program-listing (%text;|listing-note)*>

<!ELEMENT listing-note (%para-elements;)*> 

<!ELEMENT command-listing (%text;)*>

<!ELEMENT screenshot (%text;)*>

<!ELEMENT property-listing (%text;)*>

<!ELEMENT biblio (%para-elements;)*> <!-- bibliographic reference -->
<!ATTLIST biblio
   name CDATA #REQUIRED
   year CDATA #REQUIRED
   url CDATA #IMPLIED>



<!-- graphics/images 
   - a figure is a standalone labelled images
   - an inline graphic should be placed in-situ (without any label) -->
<!ELEMENT figure (description?,(caption|%section-elements;)*)>
<!ATTLIST figure
	width CDATA  "100%"
   	wrap (yes|no) "no"
	side (left|centre|right|inside|outside) "right"	
        fileref CDATA #REQUIRED
        label CDATA #IMPLIED>

<!ELEMENT description (%text;)*>

<!ELEMENT inline-graphic (description?,(annotation)*)>
<!ATTLIST inline-graphic
   width CDATA  "80%"
   	wrap (yes|no) "no"
	side (left|centre|right|inside|outside) "centre"
        fileref CDATA #REQUIRED>
	
<!ELEMENT annotation (para)*>
<!ATTLIST annotation
	x CDATA #REQUIRED
	y CDATA #REQUIRED>
	

<!-- panel
   - a standalone labelled section of text and image -->
<!ELEMENT panel (caption,(subheading|para|list|program-listing|
        command-listing|property-listing|inline-graphic|comment|index)*)>
<!ATTLIST panel
        label CDATA #IMPLIED>

<!ELEMENT caption (%para-elements;)*>




<!-- subelements - these are all found within paras, listings etc. -->
<!ELEMENT em (#PCDATA)>  <!-- emphasis -->
<!ELEMENT ital (#PCDATA)>  <!-- italics -->
<!ELEMENT rephrase (#PCDATA)>  <!-- rephrase -->

<!-- class definitions -->
<!ELEMENT code (#PCDATA)>  <!-- Java code -->

<!ELEMENT class (%text;)*>

<!ELEMENT method (%text;)*>

<!ELEMENT variable (%text;)*>

<!-- visible aspects -->
<!ELEMENT object (#PCDATA)>

<!ELEMENT menu (#PCDATA)>

<!ELEMENT field (#PCDATA)>

<!-- other programming elements - filepaths and property entries -->
<!ELEMENT path (%text;)*>

<!ELEMENT property (%text;)*>


<!-- links -->
<!-- internal - to other parts of the document -->
<!ELEMENT see (%para-elements;)*>
<!ATTLIST see
   file CDATA #IMPLIED
   label CDATA #REQUIRED
   comment CDATA #IMPLIED>

<!ELEMENT anchor EMPTY>
<!ATTLIST anchor
        label CDATA #REQUIRED>

<!-- external - to web sites -->
<!ELEMENT weblink (#PCDATA)>
<!ATTLIST weblink
        address CDATA #REQUIRED>

<!-- bibliographic reference -->
<!ELEMENT ref EMPTY>
<!ATTLIST ref
        name CDATA #REQUIRED
        year CDATA #REQUIRED>

<!-- index references -->
<!ELEMENT index (term, usage?)>

<!ELEMENT term (%para-elements;)*>

<!ELEMENT usage (%para-elements;)*>

=== 4DvAnCeBoY/isis/documentation/src/enterprise/configuring and running.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "./documentation.dtd">
<section>
  <title>How to Connect Components</title>

  <para>The NOF is designed to be configured and run in a number of ways,
  specifically from within a container such as <weblink
  address="http://www.springframework.org/">Spring</weblink> or <weblink
  address="http://www.picocontainer.org/">PicoContainer</weblink>. The NOF is
  a collection of components that are designed to work together to build a
  particular kind of system. By providing flexibility in the configuration of
  the system it allows you to set up stand alone exploration demo, a client,
  or a server system from same set of components.</para>

  <para>Each component in the NOF must be told of the other components it
  depends upon, and must be configured with its own parameters. To make this
  as flexible as possible the components are defined as Java classes and each
  dependency and property is declared as an mutator method (i.e. in the form
  <method>set<ital>Property</ital>(<ital>Type</ital>
  <ital>value</ital>)</method>); both Java and .Net compatible methods have
  been used in all classes to allow configuration from both platforms. At its
  most basic the NOF can be configured and run by writing a Java or .Net
  program that creates each component and sets up its parameters and
  dependencies, as the example below shows.</para>

  <program-listing>ObjectStorePersistor persistor = new ObjectStorePersistor();
persistor.setObjectStore(objectStore);
persistor.setPersistAlgorithm(persistAlgorithm);
persistor.setCheckObjectsForDirtyFlag(true);

nakedObjects.setObjectPersistor(persistor);
</program-listing>

  <para>This sets up the persistor by creating a
  <class>ObjectStorePersistor</class> instance and specifying its dependencies
  as the object store and persist algorithm, and setting up the 'check objects
  for dirty' flag. The last line then takes this new component and sets it up
  as a dependent of the naked objects repository
  (<class>NakedObjects</class>). See
  <class>org.nakedobjects.example.exploration.JavaExploration</class> and
  <class>org.nakedobjects.xat.AcceptanceTestCase</class> for complete
  configurations done this way.</para>

  <subheading>Properties Configuration</subheading>

  <para>A special class called <class>org.nakedobjects.app.Startup</class> is
  provided with the NOF that loads up a configuration file, which can can
  specified on the command line, that specifies what components are to be
  loaded and how they are to be configured. Using a pattern that is used in
  products such the Jetty web server and Log4J the components are specified by
  their class names and identified by property name. These names can then be
  used to set up the dependencies. The following properties do the same job as
  the Java code previously (the backslashes are line continuation
  characters).</para>

  <program-listing>nakedobjects.container.persistor=\
    org.nakedobjects.object.persistence.objectstore.ObjectStorePersistor
nakedobjects.container.persistor.objectStore=\
    org.nakedobjects.object.persistence.objectstore.inmemory.TransientObjectStore
nakedobjects.container.persistor.checkObjectsForDirtyFlag=true  
</program-listing>

  <para>The first line creates the persistor instance and assigns it the
  container object, which was described ealier - but is not shown - in the
  configuration. The second line creates the object store instance and assigns
  it to the persistor using its <method>setObjectPersistor</method>method. The
  final line similarly calls the <method>setCheckObjectsForDirtyFlag</method>
  method, passing in a literal instead of another object.</para>

  <subheading>Spring Configuration</subheading>

  <comment>to add</comment>
</section>

=== 4DvAnCeBoY/isis/documentation/src/architecture/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../documentation.dtd">
<section>
  <title>Configuration</title>

  <para>The <class>NakedObjectConfiguration</class> interface provides the
  rest of the framework with a central place to access all configuration
  properties. Each property is accessed by a fully qualified name and
  type.</para>

  <subheading>Installling this Component</subheading>

  <para>A configuration is installed by assigning an instance of
  <class>org.nakedobjects.utility.NakedObjectConfiguration</class> to the NOF
  repository. How the properties are loaded is then up to the
  implementation.</para>

  <program-listing>NakedObjects.setConfiguration(new Coniguration());</program-listing>

  <subheading>Using this Component</subheading>

  <para>The configuration component can be retrieved from
  <class>org.nakedobjects.NakedObjects</class> using the
  <method>getConfiguration</method> method.</para>

  <minorheading>Accessing properties</minorheading>

  <para>The configuration allows you to add properties to it, check it
  contains a specific property and get specific properties by name. The get
  methods return specific type such as boolean, integer, font, color and
  strings.</para>

  <minorheading>Programmatically configuring options</minorheading>

  <para>All of the configuration options can be set programmatically, which
  can be convienient when developing and running the exploration code,
  avoiding the need to create a separate configuration file. To add a
  key-value pair simply call the <method>add</method> method on the
  configuration object with a key <class>String</class> and a value
  <class>String</class>. To change the title style, for example, add the
  following to the <method>main</method> method:</para>

  <program-listing>NakedObjects.getConfiuration.add("nakedobjects.skylark.font.title", "Serif-bold-18");</program-listing>

  <comment>Add the javadoc methods</comment>
</section>

=== 4DvAnCeBoY/isis/documentation/src/object loader.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "./documentation.dtd">
<section>
  <title>Object Loader</title>

  <para>The object loader manages the domain objects in local memory, creating
  an adapter for each domain object that is in use within the system. The NOF
  only knows about the adapters and hence uses these throughout the system,
  and interacts with the domain object indirectly through the adapter. The
  adapters use the reflector to actually manipulate the domain objects. There
  should only ever be one adapter for any domain objects, so the second job
  for the loader is ensure that any time that a adapter is needed for a domain
  object it must find the existing one, if it exists, or create a new
  one.</para>

  <para>Every persistent object within the NOF has a unique identifier that is
  used identify each an every object within the object manager and when
  objects are passed between nodes on the network. Using such an identifier
  the NOF can persist relationships between objects in the persistance layer,
  and see two physical objects on separate machines as being the same logical
  object.</para>

  <subheading>How the Loader Works</subheading>

  <para>The loader holds two maps: one for the association between the domain
  object and its adapter (the <class>NakedObject</class> instance) - the
  <ital>adapter map</ital>; and another for the association between the OID
  and the adapter - the <ital>identity map</ital>. Two sets of methods are
  provided for adding objects to these maps and retrieving them later. The
  <method>create...</method> and <method>recreate...</method> methods
  generally take a domain object and return an adapter, adding the association
  to the adapter map in the process. If the object is persistent and OID is
  passed in then an association is also added to the identity map. The
  <method>get...</method> methods provide a way of retrieving known adapters
  from loader for a specified domain object or an OID.</para>

  <comment>Expand on the process of creating an adapter. - values,
  collections, objects</comment>

  <para>To keep the loader from forever growing an <method>unload</method>
  method is provided.</para>

  <para>The rest of the methods deal with the changing states of the adpaters,
  as they become persistent or are lazily loaded into memoy. When an object is
  made persistent, and is being added to persistent memory, the
  <method>madePersistent</method> method is called, enabling the loader to add
  an association to its identity map for the existing adapter and its new
  identity or OID. The <method>start</method> and <method>end</method> methods
  provide a way for the persistence and distribution mechanisms to change the
  resolved state of of lazily loaded objects in a controlled fashion,
  informing the rest of the framework whether an object is fully loaded or not
  and whether changes should be recorded or not.</para>

  <comment>Detail how ResolvedState is used &amp; what the possible states
  are</comment>

  <subheading>Installation</subheading>

  <para>The naked objects repositry needs to have a object loader installed.
  To install the loader call the <method>setObjectLoader method</method> on
  <class>NakedObjects</class> passing in an instance of
  <class>org.nakedobjects.object.NakedObjects</class>. The supplied loader -
  <class>org.nakedobjects.object.defaults.ObjectLoaderImpl</class> - is
  normally suitable, so a common configuration would be:-</para>

  <program-listing>objectLoader = new ObjectLoaderImpl();
:
:
NakedObjects.setObjectLoader(objectLoader);</program-listing>

  <subheading>Implementations</subheading>

  <para>The implementation provided with the NOF delegates its mapping and
  creation of adapters to four separate delegates: PojoAdapterMap,
  IdentityAdapterMap, ObjectFactory and AdapterFactory. These are set up using
  their accessor methods<comment>should we add a reference to configuration
  and running section?</comment>.</para>

  <subheading>Creating a New Object Loader</subheading>

  <para>Implement the interface
  org.nakedobjects.object.NakedObjectLoader.</para>

  <comment><para>Add the method details from the interface
  declaration</para></comment>
</section>

=== 4DvAnCeBoY/isis/documentation/src/viewer properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "./documentation.dtd">
<section numbered="on">
  <title>Viewer properties</title>

  <para>Fonts can be specified for the following areas:-</para>

  <list>
    <para>class</para>

    <para>debug</para>

    <para>label</para>

    <para>normal</para>

    <para>status</para>

    <para>title</para>
  </list>

  <para>A particular font can be specifed for an area by specifying</para>

  <property-listing>org.nakedobjects.viewer.skylark.font.&lt;area&gt;=&lt;font&gt;</property-listing>

  <para>Where the <property>&lt;area&gt;</property> is the name and the
  <property>&lt;font&gt;</property> is specified according the
  <method>Font.decode()</method> specification (<class>see
  java.awt.Font</class>). This essentially is a contationation of the name,
  style and size as below:</para>

  <property-listing>&lt;logical font name&gt;-&lt;style&gt;-&lt;point
  size&gt;</property-listing>

  <para>In addition to the font the amount of space between lines of text can
  also be specified.</para>

  <property-listing>org.nakedobjects.viewer.skylark.spacing.&lt;area&gt;=&lt;pixels&gt;</property-listing>
</section>

=== 4DvAnCeBoY/isis/documentation/src/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "./documentation.dtd">
<section>
  <title>Configuration Component</title>

  <para>The configuratiin component provides the rest of the framework with a
  central place to access all the configuration properties. Each property is
  accessed by a fully qualified name and type. The
  <class>Configuration</class> class is concrete and therefore can only be
  subclassed, but it can be instantiated using a
  <class>ConfigurationLoader</class>, which loads the properties into the
  configuration.</para>

  <subheading>Installling this Component</subheading>

  <para>A configuration is installed by instantiating the
  <class>org.nakedobjects.container.configuration.Configuration</class> class.
  To load properties into the configuration pass in
  a<class>org.nakedobjects.container.configuration.ConfigurationLoader</class>
  into the constructor.</para>

  <para>The provided <class>ConfigurationLoader</class> is
  <class>org.nakedobjects.container.configuration.ConfigurationPropertiesLoader</class>,
  which loads the properties from a Java style properties file.</para>

  <para>Normal practice is to provide the properties in Java properties file
  and set up the configuration component using the provided properties
  loader:-</para>

  <program-listing>new Configuration(new ConfigurationPropertiesLoader("file.properties", false);</program-listing>

  <para>The flag determines if the file must be found and loaded; if true and
  the file cannot be found an exception is thrown.</para>

  <subheading>Using this Component</subheading>

  <para>The configuration component can be retrieved from
  <class>org.nakedobjects.NakedObjects</class> using the
  <method>getConfiguration</method> method.</para>

  <para>The configuration allows you to add properties to it, check it
  contains a specific property and get specific properties by name. The get
  methods return specific type such as boolean, integer, font, color and
  strings.</para>

  <minorheading>Programmatically configuring options</minorheading>

  <para>All of the configuration options can be set programmatically, which
  can be convienient when developing and running the exploration code,
  avoiding the need to create a separate configuration file. To add a
  key-value pair simply call the <method>add</method> method on the
  configuration object with a key <class>String</class> and a value
  <class>String</class>. To change the title style, for example, add the
  following to the <method>main</method> method:</para>

  <program-listing>NakedObjects.getConfiuration.add("nakedobjects.skylark.font.title", "Serif-bold-18");</program-listing>

  <comment>Add the javadoc methods</comment>

  <subheading>Extending this Component</subheading>

  <para>Implement a new
  <class>org.nakedobjects.container.configuration.ConfigurationLoader</class>
  and return the set of properties via the <method>getProperties()</method>
  method. Create an instance of this new class and pass into the constructor
  of the <class>Configuration</class> class when instantiating that.</para>
</section>

=== 4DvAnCeBoY/isis/documentation/src/enterprise/security.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../documentation.dtd">
<section>
  <title>How to Control User Access to Object and Methods</title>

  <para>A basic form of authorisation control is provided by the NOF through
  the decoration of the reflection peers (ActionPeer, OneToOnePeer and
  OneToManyPeer) and though an interface to an external security
  service.</para>

  <subheading>How it works</subheading>

  <para>The reflection peers <class>ActionAuthorisation</class>,
  <class>OneToOneAuthorisation</class> and
  <class>OneToManyAuthorisation</class> forward requests to the
  <class>AuthorisationManager</class> (all from the
  <class>org.nakedobjects.object.security</class> package) when the
  <class>ActionImpl</class>, <class>OneToOneAssociationImpl</class> and
  <class>OneToOneAssociationImpl</class> (from
  <class>org.nakedobjects.object.reflect</class>) classes call their
  <method>isAuthorised</method> method. The authorisation manager interface
  has only one method that determine if the action or field should be visible.
  This method takes a <class>Session</class> object and a
  <class>MemberIdentifier</class> (both from
  <class>org.nakedobjects.object</class>). The identifier contains the class
  name, member name and array of parameter names for the method to be
  executed, allowing the external system to determine what method is trying to
  be executed without any reference ti the NOF itself.</para>

  <subheading>Installation</subheading>

  <para>To install security you need to add the peer factory
  <class>org.nakedobjects.object.security.SecurityPeerFactory</class> to the
  specification loader, along with any other needed peer factories. This
  factory needs to be set up with a security manager via its
  <method>setAuthorisationManager</method> method. The following example does
  just that:-</para>

  <program-listing>JavaSpecificationLoader specificationLoader = new JavaSpecificationLoader();

SecrityPeerFactory peerFactory = new SecrityPeerFactory();
peerFactory.setAuthorisationManager(securityManager);
ReflectionPeerFactory[] factories = new ReflectionPeerFactory[] {
    peerFactory
};
specificationLoader.setReflectionPeerFactories(factories);</program-listing>

  <subheading>Extending this component</subheading>

  <para>To create a security manager (none are provided with the NOF) you must
  implement the
  <class>org.nakedobjects.object.security.AuthorisationManager</class> class,
  which is a <class>NakedObjectComponent</class>.</para>

  <para><comment>Add in javadoc refs</comment></para>
</section>

=== 4DvAnCeBoY/isis/documentation/src/architecture/repository.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "../documentation.dtd">
<section>
  <title>Repository</title>

  <para><class>NakedObjects</class> is a respository for NOF providing a
  central access point for the <class>Configuration</class>,
  <class>NakedObjectsLoader</class>, and <class>ObjectManager</class> objects
  amongst other things. It is a abstract singleton that expects it concrete
  subclass to store these details. There are a number of implementation within
  the NOF, specifically one for client side use
  (<class>NakedObjectsClient)</class>, which is for use in applications where
  there is one of each component and hence no ssharing. The other main
  implementation is for server use (<class>NakedObjectsByThread</class>),
  which keeps the one instance of each component for each thread in
  use.</para>

  <subheading>Using the Repository</subheading>

  <para>To install a repository instantiate an instance of it, it will act as
  singleton storing a reference to itself.</para>

  <para>To get hold of one of the components held by the repository use the
  static get methods on the <class>NakedObjects</class> class.</para>
</section>

=== 4DvAnCeBoY/isis/documentation/src/architecture/nakedobjects-repository.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section SYSTEM "./documentation.dtd">
<section>
  <title>Repository</title>

  <para><class>NakedObjects</class> is a respository for NOF providing a
  central access point for the <class>Configuration</class>,
  <class>NakedObjectsLoader</class>, and <class>ObjectManager</class> objects
  amongst other things. It is a abstract singleton that expects it concrete
  subclass to store these details. There are a number of implementation within
  the NOF, specifically one for client side use
  (<class>NakedObjectsClient)</class>, which is for use in applications where
  there is one of each component and hence no ssharing. The other main
  implementation is for server use (<class>NakedObjectsByThread</class>),
  which keeps the one instance of each component for each thread in
  use.</para>

  <subheading>Using the Repository</subheading>

  <para>To install a repository instantiate an instance, it acts as singleton
  storing a reference to itself. The NOF provides three
  implementations:-</para>

  <list>
    <item2>
      <label><class>org.nakedonbjects.NakedObjectsClient</class></label>

      <para>a single-threaded version that simply store all the component
      references and will return those components regardless of the thread
      that it call with.</para>
    </item2>

    <item2>
      <label><class>org.nakedonbjects.NakedObjectsByThread</class></label>

      <para>a multi-threaded version that stores a unique reference to each
      for each thread in use. This way every thread has it own configuration,
      loader, object manager etc.</para>
    </item2>

    <item2>
      <label><class>org.nakedonbjects.NakedObjectsPipe</class></label>

      <para>a dual context version that provides one context for the server
      thread, and a second context for all other threads. This is used for
      running a client-server configuration in a single memory space, where
      the threads are used to keep the components separate.</para>
    </item2>
  </list>

  <para>To get hold of one of the components held by the repository use the
  static get methods on the <class>NakedObjects</class> class.</para>

  <subheading>Extending the Repository</subheading>

  <para>To create your own repository extend the
  <class>org.nakedobjects.NakedObjects</class> and implement the set methods
  for initialising the references, and the set of methods
  (<method>configuration</method>, <method>currentSession</method>,
  <method>objectLoader</method>, <method>objectManager</method>, and
  <method>specificationLoader</method>) that pass up the component references
  to the static accessors.</para>
</section>
